# permissions for end users to view pachyderms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pachyderm-viewer-role
rules:
- apiGroups:
  - aiml.pachyderm.com
  resources:
  - pachyderms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aiml.pachyderm.com
  resources:
  - pachyderms/status
  verbs:
  - get
